### ISSUE TITLE
The TM_Robot_Expression.pdf

### ISSUE THREAD

**Issue by TFLQW** [TechmanRobotInc/tmr_ros1#1]
Hi~, Thanks for your package, I have a request that could you upload the TM_Robot_Expression.pdf because I cannot get the match version of the mentioned pdf in the code.

**Comment by TechmanRobotIncOwner** [comment]
please refer this document

https://assets.omron.eu/downloads/manual/en/v1/i848_tm_expression_editor_and_listen_node_reference_manual_en.pdf
