### ISSUE TITLE
Obtaining camera feed from built-in uEye camera

### ISSUE THREAD

**Issue by jvdtoorn** [TechmanRobotInc/tmr_ros1#10]
First of all, thanks for developing this ROS driver, it works very well.

Now I would like to process the camera feed of the uEye camera on ROS as well.
How can I setup the TM arm to broadcast its camera feed? Having the ability to query to current picture would also suffice.
I see some images in the `figures/` tab about connecting the camera feed to an external API, but I see no documentation of this.

**Comment by karl-exwzd** [comment]
There is some documentation related to this in the [ROS2 driver](https://github.com/TechmanRobotInc/tmr_ros2).

**Comment by jvdtoorn** [comment]
@exwzd-kk thanks for your reply, that documentation is helpful. Unfortunately it looks like it is not possible to receive a live feed with this method, only individual images over a JSON API.
