### ISSUE TITLE
[Question] Does the robot arm have a cartesian velocity command interface?

### ISSUE THREAD

**Issue by harumo11** [TechmanRobotInc/tmr_ros1#13]
Hello Developers.

First of all, I would like to apologize for posting this question that is not suitable for posting to issue.

I have a plan to purchase the TM12 robot arm for my research. 
Before purchasing, I would like to confirm the interfaces of the robot arm. 
Does this driver have a cartesian or joint velocity(on-the-fly) command interface? 

Thanks in advance.

**Comment by TechmanRobotIncOwner** [comment]
Hi, the answer is yes.
We have cartesian and joint velocity command in our driver.
