### ISSUE TITLE
TM5-700 moveit package

### ISSUE THREAD

**Issue by ganapathy-89** [TechmanRobotInc/tmr_ros1#14]
Hi, not sure if this the right place to post, but cant find the comments section so posting here,
Can please share the TM5-700 moveit package

**Comment by TechmanRobotIncOwner** [comment]
Hi, is this that you need?
https://github.com/TechmanRobotInc/tmr_ros1/tree/master/tm5_700_moveit_config

Or
https://github.com/TechmanRobotInc/tmr_ros1/tree/master/tm5-700-moveit_config
