### ISSUE TITLE
Difference between `tmr_description` and e.g. `tm5_description` ?

### ISSUE THREAD

**Issue by danielcranston** [TechmanRobotInc/tmr_ros1#16]
Hello @TechmanRobotIncOwner,

There seems to be some redundancy between `tmr_description`, and `tm5_description` / `tm12_description`. I have some quick questions regarding this:

#### 1: If I want to run the ROS driver against a TM5, which description package should I be using?

The `tm5_700_moveit_config` uses `tm5_description`. However, I'm interested in applying the error compensation discussed in https://github.com/TechmanRobotInc/tmr_ros1/issues/15, and it seems the intended script for that lives in `tmr_description` which makes assumptions that are not valid for the `tm5_description` URDF layout (see below).

#### 2: It seems the structure of the URDFs are completely different between the `tmr_description` and the other description packages.

For instance,
* joint names: 
    - `tmr_description`: `joint_1`, `joint_2`, `joint_3`, ...
    - `tm5_description`: `shoulder_1_joint`, `shoulder_2_joint`, `elbow_joint`, ... 
* relative joint position/orientations:
    - The kinematic chain seems to be defined quite differently. See the below image which shows the visual part for the same part of the robot, as defined in `tm5_description` and `tmr_description` respectively:

![image](https://user-images.githubusercontent.com/45213235/144538909-24cf94a8-cd52-4c9b-83a8-b893a2e06568.png)

#### 3: Can you give some history of why these seemingly overlapping packages exist?

It's currently a little bit confusing to understand what you should focus on and what is potentially old/deprecated code. A short explanation here would help a lot I think!

Thank you for reading!

**Comment by TechmanRobotIncOwner** [comment]
Hi,

"tmr_description" and "tm5_description" is almost the same, the only difference is URDF coordinate. 

We will merge these two in the future.

**Comment by danielcranston** [comment]
I noticed the packages are still not merged even though this ticket was closed. Could you give an update on this @TechmanRobotIncOwner ?

**Comment by TechmanRobotIncOwner** [comment]
Hi, we are going to to upload the new model in these two months.
Thank you.
