### ISSUE TITLE
RViz real TM12 1300 doesn't move

### ISSUE THREAD

**Issue by MarcoCicognani** [TechmanRobotInc/tmr_ros1#2]
Hi, as i written in the title I'm currently trying to move a real TM12 1300 with ROS RViz.
I have installed all the requested packages (ros-melodic-desktop-full, ros-melodic-moveit, ros-melodic-industrial-core, tmr_ros1) under Ubuntu 18.04 without errors.
When I launch ROS with
```sh
source /opt/ros/melodic/setup.bash
source ${HOME}/src/BTRobot/devel/setup.bash
roslaunch tm12_moveit_config tm12_moveit_planning_execution.launch sim:=False robot_ip:=<RobotIP>
```
the robot is drawn into the RViz but in a wrong position (the home position) instead of the normal pose (which is his real position); when i move the 3d model into the RViz and clicking the Plan & Execute button the RViz writes that the script was executed succesfully, but the real robot doesn't move.

My PC and the robot are in the same LAN, no connection errors occur

**Comment by JensVanhooydonck** [comment]
I have the same issue, however the robot does move, but extremly slow. Did you solve your issue?

**Comment by TechmanRobotIncOwner** [comment]
you can type ``rosrun tm_driver tm_driver <robot_ip_address>`` to check the connection is correct or not.

If your connection is success, please paste your terminal, I will check it.
