### ISSUE TITLE
tm_driver unable to connect to TM12

### ISSUE THREAD

**Issue by sunnivam** [TechmanRobotInc/tmr_ros1#22]
Hi,
I am an engineer working on a project using the TM12 robot. I am not able to get remote connection to the robot. I am using Ubuntu 18.04 and ROS melodic. 
I have followed every step in the tutorial. I am running the listening node, set the ethernet slave and imported the data table settings. I am able to ping the robot ip from the remote computer. 

When I run
`rosrun tm_driver tm_driver 10.0.0.20`
I get the following output

![Screenshot from 2022-08-15 12-34-20](https://user-images.githubusercontent.com/110605262/184634254-67d31a27-c516-45cb-b1c3-bc57f4d9b0fb.png)

Any suggestion on why this is happening? Any help would be appreciated.

**Comment by IGGIKOR** [comment]
Hi, I am having the same exact problem as you, did you solve it? If so, how??

**Comment by sunnivam** [comment]
Yes, I was connected to the wrong ethernet port on the controller. Once I tried the other port it was working fine

**Comment by mojervico** [comment]
Hello, Can you indicate to which port did you connected please?. In the image below 1,2 or 3? 

![image](https://github.com/TechmanRobotInc/tmr_ros1/assets/98605962/94efeb91-0939-4aa1-a9ed-1a08693b12b8)
