### ISSUE TITLE
Cannot find Setting/Connection page

### ISSUE THREAD

**Issue by cloudhy417-ntu** [TechmanRobotInc/tmr_ros1#3]
In our tm5_900 robot arm, we cannot find the Setting/Connection page in the step 3.
Our system version is 1.72.3800.

**Comment by jvdtoorn** [comment]
I'm facing the same problem, also with the 1.72.38 version. I suspect that this driver uses a more up-to-date variant, so I'm currently updating TMFlow. I will update this thread once I know more.

**Comment by jvdtoorn** [comment]
My suspicion was correct: I've updated to system version 1.80.53 and now the 'setting/connection' page is available.

**Comment by karl-exwzd** [comment]
The instructions should also mention that the robot must be set to manual mode using the remote `M/A` button to access these pages, as they cannot be accessed in auto mode.

**Comment by chicostate-mmem** [comment]
> The instructions should also mention that the robot must be set to manual mode using the remote `M/A` button to access these pages, as they cannot be accessed in auto mode.

Robot interface warns you that you cannot access in auto mode. I think more importantly this readMe.md file should incorporate the compatible -or minimum- version of the TM Flow.

**Comment by karl-exwzd** [comment]
@chicostate-mmem I mentioned this because it took me several minutes to figure it out, pretty much by chance, as I was not very familiar with this part, despite having worked with the robot for about a year. The previous software I used to control the robot did not have this requirement.

Good point about the TMFlow version.

**Comment by chicostate-mmem** [comment]
@exwzd-kk I would agree with you in the case there is no explicit warning by the robotic system when it runs. If your comment is about the need of having different modes of the system such as auto, manual, remote auto, that is about the architecture of the software and the features which come with it.
It is hard to highlight which approach is better without really seeing and understanding the comparison. Based on my experience almost with any possible robotic system (e.g., ABB, Yaskawa, UR, Staubli, Aubo, etc.), I don't see Techman's mode approach as problematic. There are more pressing issues in the software architecture of flowchart and other Ux items in the software -yet these are not the point of this discussion.
I think having the version on the documentation is a no-brainer and also one of the well-known practices in any documentation.

**Comment by karl-exwzd** [comment]
@chicostate-mmem Indeed, I just meant that the having the robot in manual mode, through the use of the `M/A` button, should be mentioned in the README.md of this repository.

I don't think asking for an explicit warning is realistic, unless I contributed to the effort. The mode approach is perfectly fine and it's none of my business to try and change it 😛
